version: 2.1

executors:
  go-executor:
    docker:
      - image: circleci/golang:1.15

jobs:
  lint-test:
    executor: go-executor
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: go fmt
          command: test -z $(go fmt ./...)
      - run: 
          name: go get
          command: go get -v -t -d ./...
      - run:
          name: go test
          command: go test -v ./...

workflows:
  version: 2
  build_algos:
    jobs:
      - lint-test
